# Generated by Django 4.2.2 on 2023-06-24 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='deadline_datetime',
            new_name='deadline',
        ),
    ]
